export interface Target {
  id: string;
  label: string;
  /** Output path relative to cwd. */
  outputPath: string;
  /** Transform the source body into this tool's file format (full-file / "file" mode). */
  render: (body: string) => string;
  /**
   * Whether this target supports managed-block injection ("block" mode).
   * Markdown-style files (CLAUDE.md, GEMINI.md, copilot) do — developers often
   * hand-edit them, so we preserve their content. Files with a strict format
   * (Cursor's `.mdc` frontmatter, Windsurf's plain rules) are always full-file.
   */
  blockable: boolean;
}

const BANNER =
  "Generated by onerule from AGENTS.md. Do not edit directly — edit AGENTS.md and run `onerule sync`.";

/** Markdown / HTML-comment banner for tools that read Markdown. */
function mdBanner(): string {
  return `<!-- ${BANNER} -->`;
}

/** Plain-text banner for non-Markdown rule files. */
function textBanner(): string {
  return `# ${BANNER}`;
}

/**
 * The target registry. Adding support for a new agent is a single entry here
 * — that is the entire extensibility story for v0.1, and makes a great
 * good-first-issue.
 */
export const TARGETS: Record<string, Target> = {
  claude: {
    id: "claude",
    label: "Claude Code",
    outputPath: "CLAUDE.md",
    render: (body) => `${mdBanner()}\n\n${body}\n`,
    blockable: true,
  },
  copilot: {
    id: "copilot",
    label: "GitHub Copilot",
    outputPath: ".github/copilot-instructions.md",
    render: (body) => `${mdBanner()}\n\n${body}\n`,
    blockable: true,
  },
  gemini: {
    id: "gemini",
    label: "Gemini CLI",
    outputPath: "GEMINI.md",
    render: (body) => `${mdBanner()}\n\n${body}\n`,
    blockable: true,
  },
  cursor: {
    id: "cursor",
    label: "Cursor",
    outputPath: ".cursor/rules/onerule.mdc",
    render: (body) =>
      [
        "---",
        "description: Project rules (generated by onerule)",
        "globs:",
        "alwaysApply: true",
        "---",
        "",
        body,
        "",
      ].join("\n"),
    blockable: false,
  },
  windsurf: {
    id: "windsurf",
    label: "Windsurf",
    outputPath: ".windsurfrules",
    render: (body) => `${textBanner()}\n\n${body}\n`,
    blockable: false,
  },
};